name = "FilePicker"
uuid = "343e72c2-1f68-4e09-982b-00772761bd7a"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
